package epo_docdb

import (
	"fmt"
	"github.com/stretchr/testify/assert"
	"strconv"
	"testing"
)

func TestReadFile(t *testing.T) {

	// process file
	exchangeObject, err := ReadFile("./test-data/AP-1206-A_302101161.xml")
	if err != nil {
		t.Error(err)
	}

	// jsonObject, err := json.MarshalIndent(exchangeObject, "", "  ")
	// fmt.Println(string(jsonObject))

	ass := assert.New(t)
	ass.NoError(err)

	// Exchange-document tag
	ass.Equal("AP", exchangeObject.CountryAttr)
	ass.Equal(20041016, exchangeObject.DateaddeddocdbAttr)
	ass.Equal(20220630, exchangeObject.DateofpreviousexchangeAttr)
	ass.Equal(20221027, exchangeObject.DateoflastexchangeAttr)
	ass.Equal(20030918, exchangeObject.DatepublAttr)
	ass.Equal("1206", exchangeObject.DocnumberAttr)
	ass.Equal("22179393", exchangeObject.FamilyidAttr)
	ass.Equal("381754736", exchangeObject.DocidAttr)
	ass.Equal("YES", exchangeObject.IsrepresentativeAttr)
	ass.Equal("A", exchangeObject.KindAttr)
	ass.Equal("EP", exchangeObject.OriginatingofficeAttr)
	ass.Equal("A", exchangeObject.StatusAttr)

	// bibliographic-data
	// publication-reference
	ass.Equal("publication-reference", exchangeObject.ExchBibliographicdata.ExchPublicationreference[0].XMLName.Local)
	ass.Equal("docdb", exchangeObject.ExchBibliographicdata.ExchPublicationreference[0].DataformatAttr)
	ass.Equal("document-id", exchangeObject.ExchBibliographicdata.ExchPublicationreference[0].Documentid.XMLName.Local)
	ass.Equal("en", exchangeObject.ExchBibliographicdata.ExchPublicationreference[0].Documentid.LangAttr)
	ass.Equal("AP", exchangeObject.ExchBibliographicdata.ExchPublicationreference[0].Documentid.Country)
	//ass.Equal("doc-number", exchangeObject.ExchBibliographicdata.ExchPublicationreference[0].Documentid.Docnumber.XMLName.Local)
	ass.Equal("1206", *exchangeObject.ExchBibliographicdata.ExchPublicationreference[0].Documentid.Docnumber)
	//ass.Equal("kind", exchangeObject.ExchBibliographicdata.ExchPublicationreference[0].Documentid.Kind.XMLName.Local)
	ass.Equal("A", *exchangeObject.ExchBibliographicdata.ExchPublicationreference[0].Documentid.Kind)
	ass.Equal(20030918, exchangeObject.ExchBibliographicdata.ExchPublicationreference[0].Documentid.Date)

	ass.Equal("publication-reference", exchangeObject.ExchBibliographicdata.ExchPublicationreference[1].XMLName.Local)
	ass.Equal("epodoc", exchangeObject.ExchBibliographicdata.ExchPublicationreference[1].DataformatAttr)
	//ass.Equal("doc-number", exchangeObject.ExchBibliographicdata.ExchPublicationreference[1].Documentid.Docnumber.XMLName.Local)
	ass.Equal("AP1206", *exchangeObject.ExchBibliographicdata.ExchPublicationreference[1].Documentid.Docnumber)

	ass.Equal("publication-reference", exchangeObject.ExchBibliographicdata.ExchPublicationreference[2].XMLName.Local)
	ass.Equal("original", exchangeObject.ExchBibliographicdata.ExchPublicationreference[2].DataformatAttr)
	ass.Equal("AP 1206", *exchangeObject.ExchBibliographicdata.ExchPublicationreference[2].Documentid.Docnumber)

	// classification-ipc
	ass.Equal("classification-ipc", exchangeObject.ExchBibliographicdata.ExchClassificationipc.XMLName.Local)
	ass.Equal("edition", exchangeObject.ExchBibliographicdata.ExchClassificationipc.Edition.XMLName.Local)
	ass.Equal("7", exchangeObject.ExchBibliographicdata.ExchClassificationipc.Edition.Value)
	ass.Equal("main-classification", exchangeObject.ExchBibliographicdata.ExchClassificationipc.Mainclassification[0].XMLName.Local)
	ass.Equal("7A 61K   9/16   A", exchangeObject.ExchBibliographicdata.ExchClassificationipc.Mainclassification[0].Value)

	for i := 0; i <= 17; i++ {
		ass.Equal(strconv.Itoa(i+1), exchangeObject.ExchBibliographicdata.ExchClassificationsipcr.Classificationipcr[i].SequenceAttr)
	}

	ass.Equal("classifications-ipcr", exchangeObject.ExchBibliographicdata.ExchClassificationsipcr.XMLName.Local)
	ass.Equal("A61K   9/16        20060101A I20051008RMEP", *exchangeObject.ExchBibliographicdata.ExchClassificationsipcr.Classificationipcr[0].Text)
	ass.Equal("A61K   9/32        20060101ALI20030127BMRU", *exchangeObject.ExchBibliographicdata.ExchClassificationsipcr.Classificationipcr[1].Text)
	ass.Equal("A61K   9/48        20060101ALI20030127BMRU", *exchangeObject.ExchBibliographicdata.ExchClassificationsipcr.Classificationipcr[2].Text)
	ass.Equal("A61K   9/50        20060101A I20051008RMEP", *exchangeObject.ExchBibliographicdata.ExchClassificationsipcr.Classificationipcr[3].Text)
	ass.Equal("A61K   9/54        20060101A I20051110RMEP", *exchangeObject.ExchBibliographicdata.ExchClassificationsipcr.Classificationipcr[4].Text)
	ass.Equal("A61K   9/62        20060101A I20051110RMEP", *exchangeObject.ExchBibliographicdata.ExchClassificationsipcr.Classificationipcr[5].Text)
	ass.Equal("A61K   9/64        20060101A I20060521RMUS", *exchangeObject.ExchBibliographicdata.ExchClassificationsipcr.Classificationipcr[6].Text)
	ass.Equal("A61K  31/22        20060101ALI20051220RMJP", *exchangeObject.ExchBibliographicdata.ExchClassificationsipcr.Classificationipcr[7].Text)
	ass.Equal("A61K  31/522       20060101A I20051110RMEP", *exchangeObject.ExchBibliographicdata.ExchClassificationsipcr.Classificationipcr[8].Text)
	ass.Equal("A61K  31/704       20060101ALI20051220RMJP", *exchangeObject.ExchBibliographicdata.ExchClassificationsipcr.Classificationipcr[9].Text)
	ass.Equal("A61K  31/7048      20060101ALI20051220RMJP", *exchangeObject.ExchBibliographicdata.ExchClassificationsipcr.Classificationipcr[10].Text)
	ass.Equal("A61K  31/708       20060101ALI20051220RMJP", *exchangeObject.ExchBibliographicdata.ExchClassificationsipcr.Classificationipcr[11].Text)
	ass.Equal("A61K  47/02        20060101ALI20051220RMJP", *exchangeObject.ExchBibliographicdata.ExchClassificationsipcr.Classificationipcr[12].Text)
	ass.Equal("A61K  47/14        20060101ALI20051220RMJP", *exchangeObject.ExchBibliographicdata.ExchClassificationsipcr.Classificationipcr[13].Text)
	ass.Equal("A61K  47/32        20060101ALI20051220RMJP", *exchangeObject.ExchBibliographicdata.ExchClassificationsipcr.Classificationipcr[14].Text)
	ass.Equal("A61K  47/36        20060101ALI20051220RMJP", *exchangeObject.ExchBibliographicdata.ExchClassificationsipcr.Classificationipcr[15].Text)
	ass.Equal("A61K  47/38        20060101ALI20051220RMJP", *exchangeObject.ExchBibliographicdata.ExchClassificationsipcr.Classificationipcr[16].Text)
	ass.Equal("A61P  31/18        20060101A I20051110RMEP", *exchangeObject.ExchBibliographicdata.ExchClassificationsipcr.Classificationipcr[17].Text)

	// patent classification
	for i := 0; i <= 7; i++ {
		ass.Equal(strconv.Itoa(i+1), exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[i].SequenceAttr)
		ass.Equal("patent-classification", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[i].XMLName.Local)
		ass.Equal("classification-scheme", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[i].Classificationscheme.XMLName.Local)
		ass.Equal("CPCI", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[i].Classificationscheme.SchemeAttr)
		ass.Equal("B", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[i].Classificationstatus)
		ass.Equal("H", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[i].Classificationdatasource)
		ass.Equal("action-date", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[i].Actiondate.XMLName.Local)
	}

	ass.Equal("A61K   9/1652", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[0].Classificationsymbol)
	ass.Equal("I", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[0].Classificationvalue)
	ass.Equal("L", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[0].Symbolposition)
	ass.Equal("EP", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[0].Classificationscheme.OfficeAttr)
	ass.Equal(20130101, exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[0].Actiondate.Date)

	ass.Equal("A61K   9/485", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[1].Classificationsymbol)
	ass.Equal("A", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[1].Classificationvalue)
	ass.Equal("L", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[1].Symbolposition)
	ass.Equal("EP", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[1].Classificationscheme.OfficeAttr)
	ass.Equal(20130101, exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[1].Actiondate.Date)

	ass.Equal("A61K   9/501", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[2].Classificationsymbol)
	ass.Equal("I", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[2].Classificationvalue)
	ass.Equal("L", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[2].Symbolposition)
	ass.Equal("EP", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[2].Classificationscheme.OfficeAttr)
	ass.Equal(20130101, exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[2].Actiondate.Date)

	ass.Equal("A61K   9/5015", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[3].Classificationsymbol)
	ass.Equal("A", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[3].Classificationvalue)
	ass.Equal("L", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[3].Symbolposition)
	ass.Equal("EP", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[3].Classificationscheme.OfficeAttr)
	ass.Equal(20130101, exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[3].Actiondate.Date)

	ass.Equal("A61K   9/5026", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[4].Classificationsymbol)
	ass.Equal("I", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[4].Classificationvalue)
	ass.Equal("F", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[4].Symbolposition)
	ass.Equal("EP", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[4].Classificationscheme.OfficeAttr)
	ass.Equal(20130101, exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[4].Actiondate.Date)

	ass.Equal("A61K   9/5073", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[5].Classificationsymbol)
	ass.Equal("I", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[5].Classificationvalue)
	ass.Equal("L", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[5].Symbolposition)
	ass.Equal("EP", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[5].Classificationscheme.OfficeAttr)
	ass.Equal(20130101, exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[5].Actiondate.Date)

	ass.Equal("A61P  31/18", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[6].Classificationsymbol)
	ass.Equal("I", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[6].Classificationvalue)
	ass.Equal("L", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[6].Symbolposition)
	ass.Equal("L", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[6].Symbolposition)
	ass.Equal("EP", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[6].Classificationscheme.OfficeAttr)
	ass.Equal(20200327, exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[6].Actiondate.Date)

	ass.Equal("A61K   9/16", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[7].Classificationsymbol)
	ass.Equal("I", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[7].Classificationvalue)
	ass.Equal("F", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[7].Symbolposition)
	ass.Equal("EP", exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[7].Classificationscheme.OfficeAttr)
	ass.Equal(20160901, exchangeObject.ExchBibliographicdata.ExchPatentclassifications.Patentclassification[7].Actiondate.Date)

	// application reference
	ass.Equal("application-reference", exchangeObject.ExchBibliographicdata.ExchApplicationreference[0].XMLName.Local)
	ass.Equal("NO", exchangeObject.ExchBibliographicdata.ExchApplicationreference[0].IsrepresentativeAttr)
	ass.Equal("470406", exchangeObject.ExchBibliographicdata.ExchApplicationreference[0].DocidAttr)
	ass.Equal("docdb", exchangeObject.ExchBibliographicdata.ExchApplicationreference[0].DataformatAttr)
	ass.Equal("document-id", exchangeObject.ExchBibliographicdata.ExchApplicationreference[0].Documentid.XMLName.Local)
	ass.Equal("AP", exchangeObject.ExchBibliographicdata.ExchApplicationreference[0].Documentid.Country)
	ass.Equal("2000001988", *exchangeObject.ExchBibliographicdata.ExchApplicationreference[0].Documentid.Docnumber)
	// ass.Equal("kind", exchangeObject.ExchBibliographicdata.ExchApplicationreference[0].Documentid.Kind.XMLName.Local)
	ass.Equal("A", *exchangeObject.ExchBibliographicdata.ExchApplicationreference[0].Documentid.Kind)
	ass.Equal(19980804, exchangeObject.ExchBibliographicdata.ExchApplicationreference[0].Documentid.Date)

	ass.Equal("application-reference", exchangeObject.ExchBibliographicdata.ExchApplicationreference[1].XMLName.Local)
	ass.Equal("epodoc", exchangeObject.ExchBibliographicdata.ExchApplicationreference[1].DataformatAttr)
	ass.Equal("document-id", exchangeObject.ExchBibliographicdata.ExchApplicationreference[1].Documentid.XMLName.Local)
	ass.Equal("AP19200001988", *exchangeObject.ExchBibliographicdata.ExchApplicationreference[1].Documentid.Docnumber)

	ass.Equal("application-reference", exchangeObject.ExchBibliographicdata.ExchApplicationreference[2].XMLName.Local)
	ass.Equal("original", exchangeObject.ExchBibliographicdata.ExchApplicationreference[2].DataformatAttr)
	ass.Equal("document-id", exchangeObject.ExchBibliographicdata.ExchApplicationreference[2].Documentid.XMLName.Local)
	ass.Equal("AP/P/2000/001988", *exchangeObject.ExchBibliographicdata.ExchApplicationreference[2].Documentid.Docnumber)

	// language of publication
	ass.Equal("language-of-publication", exchangeObject.ExchBibliographicdata.ExchLanguageofpublication.XMLName.Local)
	ass.Equal("en", exchangeObject.ExchBibliographicdata.ExchLanguageofpublication.Value)

	ass.Equal("priority-claims", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.XMLName.Local)
	ass.Equal("priority-claim", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[0].XMLName.Local)
	ass.Equal("1", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[0].SequenceAttr)
	ass.Equal("docdb", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[0].DataformatAttr)
	ass.Equal("document-id", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[0].Documentid.XMLName.Local)
	ass.Equal("8359798", *exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[0].Documentid.Docnumber)

	// ass.Equal("kind", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[0].Documentid.Kind.XMLName.Local)
	ass.Equal("A", *exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[0].Documentid.Kind)
	ass.Equal("US", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[0].Documentid.Country)
	ass.Equal(19980522, exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[0].Documentid.Date)
	ass.Equal("Y", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[0].ExchPriorityactiveindicator)

	ass.Equal("priority-claim", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[1].XMLName.Local)
	ass.Equal("1", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[1].SequenceAttr)
	ass.Equal("epodoc", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[1].DataformatAttr)
	ass.Equal("document-id", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[1].Documentid.XMLName.Local)
	ass.Equal("US19980083597", *exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[1].Documentid.Docnumber)

	ass.Equal("priority-claim", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[2].XMLName.Local)
	ass.Equal("2", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[2].SequenceAttr)
	ass.Equal("docdb", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[2].DataformatAttr)
	ass.Equal("document-id", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[2].Documentid.XMLName.Local)
	ass.Equal("9816128", *exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[2].Documentid.Docnumber)
	// ass.Equal("kind", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[2].Documentid.Kind.XMLName.Local)
	ass.Equal("W", *exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[2].Documentid.Kind)
	ass.Equal("US", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[2].Documentid.Country)
	ass.Equal(19980804, exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[2].Documentid.Date)
	ass.Equal("W", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[2].ExchPrioritylinkagetype)
	ass.Equal("N", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[2].ExchPriorityactiveindicator)

	ass.Equal("priority-claim", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[3].XMLName.Local)
	ass.Equal("2", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[3].SequenceAttr)
	ass.Equal("epodoc", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[3].DataformatAttr)
	ass.Equal("document-id", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[3].Documentid.XMLName.Local)
	ass.Equal("WO1998US16128", *exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[3].Documentid.Docnumber)

	ass.Equal("priority-claim", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[4].XMLName.Local)
	ass.Equal("1", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[4].SequenceAttr)
	ass.Equal("original", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[4].DataformatAttr)
	ass.Equal("document-id", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[4].Documentid.XMLName.Local)
	ass.Equal("PCT/US98/16128", *exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[4].Documentid.Docnumber)

	ass.Equal("priority-claim", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[5].XMLName.Local)
	ass.Equal("2", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[5].SequenceAttr)
	ass.Equal("original", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[5].DataformatAttr)
	ass.Equal("document-id", exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[5].Documentid.XMLName.Local)
	ass.Equal("09/083,597", *exchangeObject.ExchBibliographicdata.ExchPriorityclaims.ExchPriorityclaim[5].Documentid.Docnumber)

	// parties
	ass.Equal("parties", exchangeObject.ExchBibliographicdata.ExchParties.XMLName.Local)
	ass.Equal("applicants", exchangeObject.ExchBibliographicdata.ExchParties.ExchApplicants.XMLName.Local)
	ass.Equal("applicant", exchangeObject.ExchBibliographicdata.ExchParties.ExchApplicants.ExchApplicant[0].XMLName.Local)
	ass.Equal("1", exchangeObject.ExchBibliographicdata.ExchParties.ExchApplicants.ExchApplicant[0].SequenceAttr)
	ass.Equal("docdb", exchangeObject.ExchBibliographicdata.ExchParties.ExchApplicants.ExchApplicant[0].DataformatAttr)
	ass.Equal("A", exchangeObject.ExchBibliographicdata.ExchParties.ExchApplicants.ExchApplicant[0].StatusAttr)
	ass.Equal("applicant-name", exchangeObject.ExchBibliographicdata.ExchParties.ExchApplicants.ExchApplicant[0].ExchApplicantname[0].XMLName.Local)
	ass.Equal("name", exchangeObject.ExchBibliographicdata.ExchParties.ExchApplicants.ExchApplicant[0].ExchApplicantname[0].Name.XMLName.Local)
	ass.Equal("BRISTOL MYERS SQUIBB CO", exchangeObject.ExchBibliographicdata.ExchParties.ExchApplicants.ExchApplicant[0].ExchApplicantname[0].Name.Value)
	ass.Equal("residence", exchangeObject.ExchBibliographicdata.ExchParties.ExchApplicants.ExchApplicant[0].Residence.XMLName.Local)
	ass.Equal("US", exchangeObject.ExchBibliographicdata.ExchParties.ExchApplicants.ExchApplicant[0].Residence.Country)

	ass.Equal("applicant", exchangeObject.ExchBibliographicdata.ExchParties.ExchApplicants.ExchApplicant[1].XMLName.Local)
	ass.Equal("1", exchangeObject.ExchBibliographicdata.ExchParties.ExchApplicants.ExchApplicant[1].SequenceAttr)
	ass.Equal("docdba", exchangeObject.ExchBibliographicdata.ExchParties.ExchApplicants.ExchApplicant[1].DataformatAttr)
	ass.Equal("applicant-name", exchangeObject.ExchBibliographicdata.ExchParties.ExchApplicants.ExchApplicant[1].ExchApplicantname[0].XMLName.Local)
	ass.Equal("name", exchangeObject.ExchBibliographicdata.ExchParties.ExchApplicants.ExchApplicant[1].ExchApplicantname[0].Name.XMLName.Local)
	ass.Equal("BRISTOL-MYERS SQUIBB COMPANY", exchangeObject.ExchBibliographicdata.ExchParties.ExchApplicants.ExchApplicant[1].ExchApplicantname[0].Name.Value)

	ass.Equal("inventors", exchangeObject.ExchBibliographicdata.ExchParties.ExchInventors.XMLName.Local)
	ass.Equal("inventor", exchangeObject.ExchBibliographicdata.ExchParties.ExchInventors.ExchInventor[0].XMLName.Local)
	ass.Equal("inventor-name", exchangeObject.ExchBibliographicdata.ExchParties.ExchInventors.ExchInventor[0].ExchInventorname[0].XMLName.Local)
	ass.Equal("1", exchangeObject.ExchBibliographicdata.ExchParties.ExchInventors.ExchInventor[0].SequenceAttr)
	ass.Equal("docdb", exchangeObject.ExchBibliographicdata.ExchParties.ExchInventors.ExchInventor[0].DataformatAttr)

	ass.Equal("invention-title", exchangeObject.ExchBibliographicdata.ExchInventiontitle[0].XMLName.Local)
	ass.Equal("en", exchangeObject.ExchBibliographicdata.ExchInventiontitle[0].LangAttr)
	ass.Equal("docdba", exchangeObject.ExchBibliographicdata.ExchInventiontitle[0].DataformatAttr)
	ass.Equal("dates-of-public-availability", exchangeObject.ExchBibliographicdata.ExchDatesofpublicavailability.XMLName.Local)
	ass.Equal("printed-with-grant", exchangeObject.ExchBibliographicdata.ExchDatesofpublicavailability.ExchPrintedwithgrant.XMLName.Local)
	ass.Equal("document-id", exchangeObject.ExchBibliographicdata.ExchDatesofpublicavailability.ExchPrintedwithgrant.Documentid.XMLName.Local)
	ass.Equal(20030918, exchangeObject.ExchBibliographicdata.ExchDatesofpublicavailability.ExchPrintedwithgrant.Documentid.Date)

	ass.Equal("references-cited", exchangeObject.ExchBibliographicdata.ExchReferencescited.XMLName.Local)
	ass.Equal("citation", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[0].XMLName.Local)
	ass.Equal("SEA", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[0].CitedphaseAttr)
	ass.Equal("1", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[0].SequenceAttr)
	ass.Equal("patcit", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[0].Patcit.XMLName.Local)
	ass.Equal("1", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[0].Patcit.NumAttr)
	ass.Equal("US5556839A", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[0].Patcit.DnumAttr)
	ass.Equal("publication number", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[0].Patcit.DnumtypeAttr)
	ass.Equal("document-id", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[0].Patcit.Documentid.XMLName.Local)
	ass.Equal(298340634, exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[0].Patcit.Documentid.DocidAttr)
	ass.Equal("5556839", *exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[0].Patcit.Documentid.Docnumber)
	ass.Equal("US", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[0].Patcit.Documentid.Country)
	ass.Equal("5556839", *exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[0].Patcit.Documentid.Docnumber)
	// ass.Equal("kind", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[0].Patcit.Documentid.Kind.XMLName.Local)
	ass.Equal("A", *exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[0].Patcit.Documentid.Kind)
	ass.Equal("name", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[0].Patcit.Documentid.Name.XMLName.Local)
	ass.Equal("GREENE JAMES M [US], et al", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[0].Patcit.Documentid.Name.Value)
	ass.Equal(19960917, exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[0].Patcit.Documentid.Date)

	ass.Equal("citation", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[1].XMLName.Local)
	ass.Equal("SEA", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[1].CitedphaseAttr)
	ass.Equal("2", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[1].SequenceAttr)
	ass.Equal("patcit", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[1].Patcit.XMLName.Local)
	ass.Equal("2", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[1].Patcit.NumAttr)
	ass.Equal("US5510114A", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[1].Patcit.DnumAttr)
	ass.Equal("publication number", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[1].Patcit.DnumtypeAttr)
	ass.Equal("document-id", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[1].Patcit.Documentid.XMLName.Local)
	ass.Equal(301191403, exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[1].Patcit.Documentid.DocidAttr)
	ass.Equal("US", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[1].Patcit.Documentid.Country)
	ass.Equal("5510114", *exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[1].Patcit.Documentid.Docnumber)

	// ass.Equal("kind", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[1].Patcit.Documentid.Kind.XMLName.Local)
	ass.Equal("A", *exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[1].Patcit.Documentid.Kind)
	ass.Equal("name", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[1].Patcit.Documentid.Name.XMLName.Local)
	ass.Equal("BORELLA FABIO [IT], et al", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[1].Patcit.Documentid.Name.Value)
	ass.Equal(19960423, exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[1].Patcit.Documentid.Date)

	ass.Equal("citation", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[2].XMLName.Local)
	ass.Equal("SEA", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[2].CitedphaseAttr)
	ass.Equal("3", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[2].SequenceAttr)
	ass.Equal("patcit", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[2].Patcit.XMLName.Local)
	ass.Equal("3", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[2].Patcit.NumAttr)
	ass.Equal("US5326570A", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[2].Patcit.DnumAttr)
	ass.Equal("publication number", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[2].Patcit.DnumtypeAttr)
	ass.Equal("document-id", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[2].Patcit.Documentid.XMLName.Local)
	ass.Equal(302101161, exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[2].Patcit.Documentid.DocidAttr)
	ass.Equal("US", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[2].Patcit.Documentid.Country)
	ass.Equal("5326570", *exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[2].Patcit.Documentid.Docnumber)
	// ass.Equal("kind", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[2].Patcit.Documentid.Kind.XMLName.Local)
	ass.Equal("A", *exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[2].Patcit.Documentid.Kind)
	ass.Equal("name", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[2].Patcit.Documentid.Name.XMLName.Local)
	ass.Equal("RUDNIC EDWARD M [US], et al", exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[2].Patcit.Documentid.Name.Value)
	ass.Equal(19940705, exchangeObject.ExchBibliographicdata.ExchReferencescited.ExchCitation[2].Patcit.Documentid.Date)

	// abstract tag
	ass.Equal("abstract", exchangeObject.ExchAbstract[0].XMLName.Local)
	ass.Equal("docdba", exchangeObject.ExchAbstract[0].DataformatAttr)
	ass.Equal("national office", exchangeObject.ExchAbstract[0].AbstractsourceAttr)
	ass.Equal("p", exchangeObject.ExchAbstract[0].ExchP[0].XMLName.Local)
	ass.Equal(598, len(exchangeObject.ExchAbstract[0].ExchP[0].Value))
	fmt.Println(exchangeObject.ExchAbstract[0].ExchP[0].Value)

	// family member tag 1 (46)
	ass.Equal("family-member", exchangeObject.ExchPatentfamily.ExchFamilymember[0].XMLName.Local)
	ass.Equal("application-reference", exchangeObject.ExchPatentfamily.ExchFamilymember[0].ExchApplicationreference[0].XMLName.Local)
	ass.Equal("docdb", exchangeObject.ExchPatentfamily.ExchFamilymember[0].ExchApplicationreference[0].DataformatAttr)
	ass.Equal("NO", exchangeObject.ExchPatentfamily.ExchFamilymember[0].ExchApplicationreference[0].IsrepresentativeAttr)
	ass.Equal("2000001988", *exchangeObject.ExchPatentfamily.ExchFamilymember[0].ExchApplicationreference[0].Documentid.Docnumber)
	ass.Equal("publication-reference", exchangeObject.ExchPatentfamily.ExchFamilymember[0].ExchPublicationreference[0].XMLName.Local)
	ass.Equal("docdb", exchangeObject.ExchPatentfamily.ExchFamilymember[0].ExchPublicationreference[0].DataformatAttr)
	ass.Equal("document-id", exchangeObject.ExchPatentfamily.ExchFamilymember[0].ExchPublicationreference[0].Documentid.XMLName.Local)
	ass.Equal("AP", exchangeObject.ExchPatentfamily.ExchFamilymember[0].ExchPublicationreference[0].Documentid.Country)
	ass.Equal("1206", *exchangeObject.ExchPatentfamily.ExchFamilymember[0].ExchPublicationreference[0].Documentid.Docnumber)
	// ass.Equal("kind", exchangeObject.ExchPatentfamily.ExchFamilymember[0].ExchPublicationreference[0].Documentid.Kind.XMLName.Local)
	ass.Equal("A", *exchangeObject.ExchPatentfamily.ExchFamilymember[0].ExchPublicationreference[0].Documentid.Kind)
	ass.Equal("publication-reference", exchangeObject.ExchPatentfamily.ExchFamilymember[0].ExchPublicationreference[1].XMLName.Local)
	ass.Equal("epodoc", exchangeObject.ExchPatentfamily.ExchFamilymember[0].ExchPublicationreference[1].DataformatAttr)
	ass.Equal("document-id", exchangeObject.ExchPatentfamily.ExchFamilymember[0].ExchPublicationreference[1].Documentid.XMLName.Local)
	ass.Equal("AP1206", *exchangeObject.ExchPatentfamily.ExchFamilymember[0].ExchPublicationreference[1].Documentid.Docnumber)
	ass.Equal("publication-reference", exchangeObject.ExchPatentfamily.ExchFamilymember[0].ExchPublicationreference[2].XMLName.Local)
	ass.Equal("docdb", exchangeObject.ExchPatentfamily.ExchFamilymember[0].ExchPublicationreference[2].DataformatAttr)
	ass.Equal("document-id", exchangeObject.ExchPatentfamily.ExchFamilymember[0].ExchPublicationreference[2].Documentid.XMLName.Local)
	ass.Equal("AP", exchangeObject.ExchPatentfamily.ExchFamilymember[0].ExchPublicationreference[2].Documentid.Country)
	ass.Equal("2000001988", *exchangeObject.ExchPatentfamily.ExchFamilymember[0].ExchPublicationreference[2].Documentid.Docnumber)
	// ass.Equal("kind", exchangeObject.ExchPatentfamily.ExchFamilymember[0].ExchPublicationreference[2].Documentid.Kind.XMLName.Local)
	ass.Equal("A0", *exchangeObject.ExchPatentfamily.ExchFamilymember[0].ExchPublicationreference[2].Documentid.Kind)

	for i := 0; i <= 45; i++ {
		ass.Equal("family-member", exchangeObject.ExchPatentfamily.ExchFamilymember[i].XMLName.Local)
		ass.Equal("application-reference", exchangeObject.ExchPatentfamily.ExchFamilymember[i].ExchApplicationreference[0].XMLName.Local)
		ass.Equal("docdb", exchangeObject.ExchPatentfamily.ExchFamilymember[i].ExchApplicationreference[0].DataformatAttr)
		ass.Equal("document-id", exchangeObject.ExchPatentfamily.ExchFamilymember[i].ExchApplicationreference[0].Documentid.XMLName.Local)
		// ass.Equal("doc-number", exchangeObject.ExchPatentfamily.ExchFamilymember[i].ExchApplicationreference[0].Documentid.Docnumber.XMLName.Local)
		ass.Equal("publication-reference", exchangeObject.ExchPatentfamily.ExchFamilymember[i].ExchPublicationreference[0].XMLName.Local)
		ass.Equal("docdb", exchangeObject.ExchPatentfamily.ExchFamilymember[i].ExchPublicationreference[0].DataformatAttr)
		ass.Equal("document-id", exchangeObject.ExchPatentfamily.ExchFamilymember[i].ExchPublicationreference[0].Documentid.XMLName.Local)
		// ass.Equal("doc-number", exchangeObject.ExchPatentfamily.ExchFamilymember[i].ExchPublicationreference[0].Documentid.Docnumber.XMLName.Local)
		// ass.Equal("kind", exchangeObject.ExchPatentfamily.ExchFamilymember[i].ExchPublicationreference[0].Documentid.Kind.XMLName.Local)
		ass.Equal("publication-reference", exchangeObject.ExchPatentfamily.ExchFamilymember[i].ExchPublicationreference[1].XMLName.Local)
		ass.Equal("epodoc", exchangeObject.ExchPatentfamily.ExchFamilymember[i].ExchPublicationreference[1].DataformatAttr)
		ass.Equal("document-id", exchangeObject.ExchPatentfamily.ExchFamilymember[i].ExchPublicationreference[1].Documentid.XMLName.Local)
		// ass.Equal("doc-number", exchangeObject.ExchPatentfamily.ExchFamilymember[i].ExchPublicationreference[1].Documentid.Docnumber.XMLName.Local)
	}
	// 2
	ass.Equal("NO", exchangeObject.ExchPatentfamily.ExchFamilymember[2].ExchApplicationreference[0].IsrepresentativeAttr)
	ass.Equal("4342002", *exchangeObject.ExchPatentfamily.ExchFamilymember[2].ExchApplicationreference[0].Documentid.Docnumber)
	ass.Equal("application-reference", exchangeObject.ExchPatentfamily.ExchFamilymember[2].ExchApplicationreference[1].XMLName.Local)
	ass.Equal("epodoc", exchangeObject.ExchPatentfamily.ExchFamilymember[2].ExchApplicationreference[1].DataformatAttr)
	ass.Equal("document-id", exchangeObject.ExchPatentfamily.ExchFamilymember[2].ExchApplicationreference[1].Documentid.XMLName.Local)
	//ass.Equal("doc-number", exchangeObject.ExchPatentfamily.ExchFamilymember[2].ExchApplicationreference[1].Documentid.Docnumber.XMLName.Local)
	ass.Equal("AT20020000434U", *exchangeObject.ExchPatentfamily.ExchFamilymember[2].ExchApplicationreference[1].Documentid.Docnumber)
	ass.Equal("AT", exchangeObject.ExchPatentfamily.ExchFamilymember[2].ExchPublicationreference[0].Documentid.Country)
	ass.Equal("6311", *exchangeObject.ExchPatentfamily.ExchFamilymember[2].ExchPublicationreference[0].Documentid.Docnumber)
	ass.Equal("U1", *exchangeObject.ExchPatentfamily.ExchFamilymember[2].ExchPublicationreference[0].Documentid.Kind)
	ass.Equal("AT6311U", *exchangeObject.ExchPatentfamily.ExchFamilymember[2].ExchPublicationreference[1].Documentid.Docnumber)
	ass.Equal("application-reference", exchangeObject.ExchPatentfamily.ExchFamilymember[2].ExchApplicationreference[1].XMLName.Local)
	ass.Equal("epodoc", exchangeObject.ExchPatentfamily.ExchFamilymember[2].ExchApplicationreference[1].DataformatAttr)
	ass.Equal("document-id", exchangeObject.ExchPatentfamily.ExchFamilymember[2].ExchApplicationreference[1].Documentid.XMLName.Local)
	//ass.Equal("doc-number", exchangeObject.ExchPatentfamily.ExchFamilymember[2].ExchApplicationreference[1].Documentid.Docnumber.XMLName.Local)
	ass.Equal("AT20020000434U", *exchangeObject.ExchPatentfamily.ExchFamilymember[2].ExchApplicationreference[1].Documentid.Docnumber)

	// 3
	ass.Equal("NO", exchangeObject.ExchPatentfamily.ExchFamilymember[3].ExchApplicationreference[0].IsrepresentativeAttr)
	ass.Equal("98938302", *exchangeObject.ExchPatentfamily.ExchFamilymember[3].ExchApplicationreference[0].Documentid.Docnumber)
	ass.Equal("application-reference", exchangeObject.ExchPatentfamily.ExchFamilymember[3].ExchApplicationreference[1].XMLName.Local)
	ass.Equal("epodoc", exchangeObject.ExchPatentfamily.ExchFamilymember[3].ExchApplicationreference[1].DataformatAttr)
	ass.Equal("document-id", exchangeObject.ExchPatentfamily.ExchFamilymember[3].ExchApplicationreference[1].Documentid.XMLName.Local)
	ass.Equal("AT19980938302T", *exchangeObject.ExchPatentfamily.ExchFamilymember[3].ExchApplicationreference[1].Documentid.Docnumber)
	ass.Equal("AT", exchangeObject.ExchPatentfamily.ExchFamilymember[3].ExchPublicationreference[0].Documentid.Country)
	ass.Equal("311859", *exchangeObject.ExchPatentfamily.ExchFamilymember[3].ExchPublicationreference[0].Documentid.Docnumber)
	ass.Equal("T", *exchangeObject.ExchPatentfamily.ExchFamilymember[3].ExchPublicationreference[0].Documentid.Kind)
	ass.Equal("AT311859T", *exchangeObject.ExchPatentfamily.ExchFamilymember[3].ExchPublicationreference[1].Documentid.Docnumber)
	ass.Equal("application-reference", exchangeObject.ExchPatentfamily.ExchFamilymember[3].ExchApplicationreference[1].XMLName.Local)
	ass.Equal("epodoc", exchangeObject.ExchPatentfamily.ExchFamilymember[3].ExchApplicationreference[1].DataformatAttr)
	ass.Equal("document-id", exchangeObject.ExchPatentfamily.ExchFamilymember[3].ExchApplicationreference[1].Documentid.XMLName.Local)
	ass.Equal("AT19980938302T", *exchangeObject.ExchPatentfamily.ExchFamilymember[3].ExchApplicationreference[1].Documentid.Docnumber)

	// 4
	ass.Equal("NO", exchangeObject.ExchPatentfamily.ExchFamilymember[4].ExchApplicationreference[0].IsrepresentativeAttr)
	ass.Equal("8685498", *exchangeObject.ExchPatentfamily.ExchFamilymember[4].ExchApplicationreference[0].Documentid.Docnumber)
	ass.Equal("application-reference", exchangeObject.ExchPatentfamily.ExchFamilymember[4].ExchApplicationreference[1].XMLName.Local)
	ass.Equal("epodoc", exchangeObject.ExchPatentfamily.ExchFamilymember[4].ExchApplicationreference[1].DataformatAttr)
	ass.Equal("document-id", exchangeObject.ExchPatentfamily.ExchFamilymember[4].ExchApplicationreference[1].Documentid.XMLName.Local)
	ass.Equal("AU19980086854", *exchangeObject.ExchPatentfamily.ExchFamilymember[4].ExchApplicationreference[1].Documentid.Docnumber)
	ass.Equal("AU", exchangeObject.ExchPatentfamily.ExchFamilymember[4].ExchPublicationreference[0].Documentid.Country)
	ass.Equal("750911", *exchangeObject.ExchPatentfamily.ExchFamilymember[4].ExchPublicationreference[0].Documentid.Docnumber)
	ass.Equal("B2", *exchangeObject.ExchPatentfamily.ExchFamilymember[4].ExchPublicationreference[0].Documentid.Kind)
	ass.Equal("1", exchangeObject.ExchPatentfamily.ExchFamilymember[4].ExchPublicationreference[0].SequenceAttr)
	ass.Equal("AU750911B", *exchangeObject.ExchPatentfamily.ExchFamilymember[4].ExchPublicationreference[1].Documentid.Docnumber)
	ass.Equal("1", exchangeObject.ExchPatentfamily.ExchFamilymember[4].ExchPublicationreference[1].SequenceAttr)
	ass.Equal("publication-reference", exchangeObject.ExchPatentfamily.ExchFamilymember[4].ExchPublicationreference[2].XMLName.Local)
	ass.Equal("docdb", exchangeObject.ExchPatentfamily.ExchFamilymember[4].ExchPublicationreference[2].DataformatAttr)
	ass.Equal("2", exchangeObject.ExchPatentfamily.ExchFamilymember[4].ExchPublicationreference[2].SequenceAttr)
	ass.Equal("document-id", exchangeObject.ExchPatentfamily.ExchFamilymember[4].ExchPublicationreference[2].Documentid.XMLName.Local)
	// ass.Equal("kind", exchangeObject.ExchPatentfamily.ExchFamilymember[4].ExchPublicationreference[2].Documentid.Kind.XMLName.Local)
	ass.Equal("AU", exchangeObject.ExchPatentfamily.ExchFamilymember[4].ExchPublicationreference[2].Documentid.Country)
	ass.Equal("8685498", *exchangeObject.ExchPatentfamily.ExchFamilymember[4].ExchPublicationreference[2].Documentid.Docnumber)
	ass.Equal("A", *exchangeObject.ExchPatentfamily.ExchFamilymember[4].ExchPublicationreference[2].Documentid.Kind)
	ass.Equal("publication-reference", exchangeObject.ExchPatentfamily.ExchFamilymember[4].ExchPublicationreference[3].XMLName.Local)
	ass.Equal("epodoc", exchangeObject.ExchPatentfamily.ExchFamilymember[4].ExchPublicationreference[3].DataformatAttr)
	ass.Equal("2", exchangeObject.ExchPatentfamily.ExchFamilymember[4].ExchPublicationreference[3].SequenceAttr)
	ass.Equal("document-id", exchangeObject.ExchPatentfamily.ExchFamilymember[4].ExchPublicationreference[3].Documentid.XMLName.Local)
	ass.Equal("AU8685498", *exchangeObject.ExchPatentfamily.ExchFamilymember[4].ExchPublicationreference[3].Documentid.Docnumber)

}

func TestReadFileParsingErr(t *testing.T) {
	// process file
	exchangeObject, err := ReadFile("./test-data/WO-2023012807-A1_507242069.xml")
	if err != nil {
		t.Error(err)
	}
	fmt.Println(exchangeObject.ExchAbstract[0].ExchP[0].Value)
	return
}
